model_list:
  - model_name: gpt-4.1 
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: openai/gpt-4.1 ### MODEL NAME sent to `litellm.completion()` ###
      api_key: "os.environ/FREVAGPT_OPENAI_API_KEY" 
      # temperature: 0.2
  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini
      api_key: "os.environ/FREVAGPT_OPENAI_API_KEY"
  - model_name: "ministral-3:8b"
    litellm_params:
      model: "ollama_chat/ministral-3:8b"
      api_base: "http://ollama:11434"
    model_info:
      supports_function_calling: true
  - model_name: "mistral-small3.2:24b"
    litellm_params:
      model: "ollama_chat/mistral-small3.2:24b"
      api_base: "http://ollama:11434"
    model_info:
      supports_function_calling: true
  - model_name: "mistral-medium-3.5:128b"  # only available size, experimental
    litellm_params:
      model: "ollama_chat/mistral-medium-3.5:128b"
      api_base: "http://ollama:11434"
    model_info:
      supports_function_calling: true
  - model_name: "qwen3.6:35b"  # Mixture Of Experts (Number of Experts: 256) and 3B activated
    litellm_params:
      model: "ollama_chat/qwen3.6:35b"
      api_base: "http://ollama:11434" 
    model_info:
      supports_function_calling: true
  - model_name: "gemma4:26b"  # Mixture of Experts model with 4B active parameters
    litellm_params:
      model: "ollama_chat/gemma4:26b"
      api_base: "http://ollama:11434" 
    model_info:
      supports_function_calling: true
  - model_name: "mxbai-embed-large:latest"
    litellm_params:
      model: "ollama/mxbai-embed-large:latest"
      api_base: "http://ollama:11434"

litellm_settings:
  drop_params: true # If true, drop all parameters not in the model_list from the request